name: Deploy to Render

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Render CLI
        run: |
          brew tap render-oss/render
          brew install render

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render login --api-key ${{ secrets.RENDER_API_KEY }}
          render deploy --service-id i002-fitfusion-back